# Generated by Django 5.2.17 on 2026-09-21 08:46

import admissions.models
import admissions.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('photo', models.ImageField(help_text='Passport-sized photograph (max 2MB, .jpg, .jpeg, .png, .webp)', upload_to=admissions.models.applicant_photo_path, validators=[admissions.validators.validate_photo])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Browser latitude coordinate at time of submission', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Browser longitude coordinate at time of submission', max_digits=9, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('10TH_MARKSHEET', '10th Standard Marksheet'), ('12TH_MARKSHEET', '12th Standard / Higher Secondary Marksheet'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate (TC)'), ('ID_PROOF', 'Government ID Proof'), ('OTHER', 'Other Supporting Document')], max_length=30)),
                ('file', models.FileField(help_text='Document file (max 5MB, PDF, JPG, PNG)', upload_to=admissions.models.applicant_document_path, validators=[admissions.validators.validate_document])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.applicant')),
            ],
            options={
                'verbose_name': 'Applicant Document',
                'verbose_name_plural': 'Applicant Documents',
                'ordering': ['document_type'],
            },
        ),
    ]
